server:
  port: 8080

spring:
  application:
    name: OpenCodeQuestionnaireApp

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: dp
    password:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

  flyway:
    url: jdbc:h2:mem:testdb
    locations: classpath:db/migration
    user: dp
    password:
    schemas: app-db
    enabled: false
